language: node_js
sudo: false
node_js:
  - 0.10
env:
  - TAG=v0.6.9.5
install:
  - mkdir $HOME/bin
  - wget -O $HOME/purescript.tar.gz 'https://drive.google.com/uc?export=download&id=0Bx4xybkHUCukWnRmaVlaWjdIT28'
  - tar zxvf $HOME/purescript.tar.gz -C $HOME/bin purescript/psc{,i,-docs,-make} --strip-components=1
  - chmod a+x $HOME/bin/psc{,i,-docs,-make}
  - ldd $HOME/bin/psc-make
  - export PATH=$HOME/bin:$PATH
  - npm install bower gulp -g
  - npm install
  - bower install --force
script:
  - gulp less
  - gulp deploy-prod-entries-file
  - gulp deploy-prod-entries-notebook
before_deploy:
  - cp -r public slamdata
  - tar cjf slamdata.tar.bz2 slamdata
deploy:
  provider: releases
  api-key:
    secure: "TitL0gINR0xhcMdNBSFKulH7VlS+q1bAkmkWe5H5drTGesqFQprmnoHxPM8Sstfr0DGrAsSKweN/SsUpmVpK8fUE3AcK9kNqt9HXIXr2UotYa1f3jqQKc4+KRXOOf4qjEdUwYRYYMUayR4psA/mijm3WxoVG/jrOjRZAkal/NAY="
  file: slamdata.tar.bz2
  skip_cleanup: true
  on:
    repo: slamdata/slamdata
    branch: master
    tags: true
notifications:
  irc:
    channels:
      - "chat.freenode.net#slamdata"
    template:
      - "%{result}: %{repository_slug}#%{build_number} (%{branch}@%{commit}: %{author}) %{build_url}"
